name: Rust Tests

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - master

  pull_request:

jobs:
  test-rust:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: npm ci

      - name: Generate test vectors
        run: npm run generate-test-vectors --workspace js

      - name: Check generated vectors
        run: ls -la test-vectors

      - name: Run Rust tests
        run: cargo test --all-targets --all-features
